In [11]:
import numpy as np
import pandas as pd

from bokeh.plotting import figure, output_file, show, save, ColumnDataSource
from bokeh.models.tools import HoverTool

In [12]:
database = pd.read_csv('ATC_1.csv', index_col=0, encoding='latin').drop(columns=["Name"])
database

    Road Name Type 2  Total  HGV  Car  LGV  Cycle  OGV1  OGV2  Stage  Daily?
#
1         A10    M22    318   45   49   49     65    65    45      1   False
2         A10    M22    405   60   62   63     80    80    60      2   False
3         A10    M22    525   80   82   83    100   100    80      3   False
4          M1    NaN    309   39   52   43     60    50    65      1   False
5          M1    NaN    405   58   64   58     80    65    80      2   False
..        ...    ...    ...  ...  ...  ...    ...   ...   ...    ...     ...
147       A15    NaN    300   41   64   45     50    50    50      1   False
148       A15    NaN    420   61   84   65     70    70    70      2   False
149       A15     M5    600   91  134   95    100   100    80      3   False
150       A30    NaN    680  106  110   90    154    90   130      1    True
151       A30    NaN    600  100  100  100    100   100   100      1   False

[151 rows x 11 columns]

In [13]:
# instantiating the figure object
graph = figure(title="Bokeh Line Graph", 
               x_axis_label='X Axis',
               y_axis_label='Y Axis',
               tools="")

# the points to be plotted,
x = [1, 2, 3, 4, 5]
y = [5, 4, 3, 2, 1]
 
# plotting the 1st line graph
graph.line(x, x, legend_label="Line 1")
 
# plotting the 2nd line graph with a
# different color
graph.line(y, x, legend_label="Line 2",
           line_color="green")

graph.legend.title = "Title of the legend"
graph.legend.location ="top_left"
graph.legend.label_text_font_size = "17pt"

# displaying the model
show(graph)

In [14]:
del(graph)
# instantiating the figure object
graph = figure(title="Bokeh Line Graph", 
               x_axis_label='X Axis',
               y_axis_label='Y Axis',
               tools="pan, zoom_in, zoom_out, save")

# the points to be plotted,
x = [1, 2, 3, 4, 5]
y = [5, 4, 3, 2, 1]
 
# plotting the 1st line graph
graph.line(x, x, legend_label="Line 1")
 
# plotting the 2nd line graph with a
# different color
graph.line(y, x, legend_label="Line 2",
           line_color="green")

graph.legend.title = "Title of the legend"
graph.legend.location ="top_left"
graph.legend.label_text_font_size = "17pt"

# displaying the model
show(graph)

In [15]:
data = pd.read_csv("Cars.csv")

#A way of reading in a pandas dataframe to use instead of a simple series. Allows you to extract more attributes for your graph.
source = ColumnDataSource(data)

#Set the name and format of saved plots
output_file("index.html")


graph = figure(
    #Note figures still need simple series
    y_range = data["Car"],
    width = 800,
    height = 600,
    title = "Cars With Top Horsepower",
    x_axis_label = "Horsepower"
)

#Setting the features of the 'glyphs' we are using to represent our data
graph.hbar(
    y = "Car",
    right = "Horsepower",
    left = 0,
    height = 0.4,
    color = "orange",
    fill_alpha = 0.5,
    source = data
)

hover = HoverTool()
hover.tooltips = """
    <div>
        <h3>@Car</h3>
        <div><strong>Price: </strong>@Price</div>
        <div><strong>HP: </strong>@Horsepower</div>
        <div><img src="@Image" alt="" width="200" /></div>
    </div>
"""

graph.add_tools(hover)

show(graph)